parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     '%env(BDD_DEFAULT_HOST)%'
                port:     '%env(BDD_DEFAULT_PORT)%'
                dbname:   '%env(BDD_DEFAULT_DBNAME)%'
                user:     '%env(BDD_DEFAULT_USERNAME)%'
                password: '%env(BDD_DEFAULT_PASS)%'
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: false
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
