easy_admin:
    translation_domain: 'admin'
    list:
        actions: ['show']
        title: "Loc'Appart - Liste - %%entity_label%%"
    show:
        title: "Loc'Appart - Détail - %%entity_label%% (#%%entity_id%%)"
    edit:
        title: "Loc'Appart - Edition - %%entity_label%% (#%%entity_id%%)"
    new:
        title: "Loc'Appart - Ajout - %%entity_label%%"

    site_name: "Administration - Loc'Appart."

    design:
        menu:
            - { label: 'Utilisateurs' }
            - { entity: 'User', icon: 'user' }
            - { label: 'Appartements' }
            - { entity: 'Appartment', icon: 'building' }
            - { entity: 'Price', icon: 'euro' }
            - { entity: 'Message', icon: 'comment' }
            - { entity: 'Ressource', icon: 'image' }
            - { label: 'Paramètres' }
            - label: 'Lieux'
              icon: 'globe'
              children:
                - { entity: 'Region', icon: 'globe' }
                - { entity: 'Department', icon: 'globe' }
                - { entity: 'City', icon: 'globe' }
            - { entity: 'Type', icon: 'home' }
            - { entity: 'Availability', icon: 'calendar' }
            - { entity: 'Status', icon: 'calendar-check-o' }
            - { label: 'Contenus' }
            - { entity: 'News', icon: 'newspaper-o' }
        brand_color: '#008CAF'
        assets:
            favicon: '/ressources/images/static/favicon.png'

    entities:
        User:
            class: App\Entity\WebApp\User
            show:
                fields: ['date', 'email', 'firstname', 'lastname', 'gender', 'roles', { property: 'notification', type: 'boolean' }]
            list:
                fields: ['date', 'email', 'firstname', 'lastname', 'gender', 'roles', { property: 'notification', type: 'toggle' }]
            new:
                fields: ['email', 'date', 'firstname', 'lastname', 'gender', 'password', 'notification', { property: 'roles', type: 'collection' }]
            edit:
                fields: ['email', 'date', 'firstname', 'lastname', 'gender', 'notification', { property: 'roles', type: 'collection' }]
        Appartment:
            class: App\Entity\WebApp\Appartment
            list:
                fields: ['date', 'title', 'reference', 'Type', 'User', 'City', 'status']
            form:
                fields: [{ type: 'tab' , label: 'Information obligatoire' }, 'title', 'area', 'room', 'description', 'address', 'lat', 'lng', { property: 'type', type_options: { class: 'App\Entity\WebApp\Type' } }, { property: 'status', type_options: { class: 'App\Entity\WebApp\Status' } }, { property: 'user', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\WebApp\User' } }, { property: 'city', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\WebApp\City' } }, { type: 'tab' , label: 'Information complémentaire' }, 'people', 'bedroom', 'ski', 'garage', 'locker', 'information']
        Availability:
            class: App\Entity\WebApp\Availability
        City:
            class: App\Entity\WebApp\City
            list:
                fields: ['name', 'lat', 'lng', 'zip', 'Department', { property: 'Department.region.name', label: 'Region' }]
        Department:
            class: App\Entity\WebApp\Department
        Message:
            class: App\Entity\WebApp\Message
        News:
            class: App\Entity\WebApp\News
        Price:
            class: App\Entity\WebApp\Price
        Region:
            class: App\Entity\WebApp\Region
        Ressource:
            class: App\Entity\WebApp\Ressource
            disabled_actions: ['edit']
            list:
                fields: ['appartment', { property: 'path', type: 'image', base_path: '/ressources/images/uploads' }]
            show:
                fields: ['appartment', { property: 'path', type: 'image', base_path: '/ressources/images/uploads' }]
            form:
                fields: ['appartment', { property: 'file', type: 'file', label: 'Image' }]
        Status:
            class: App\Entity\WebApp\Status
            list:
                fields: ['id', 'name', 'description']
        Type:
            class: App\Entity\WebApp\Type
